{{- $appName := include "web-service.name" . }}
{{- with .Values.image }}
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: {{ $appName }}-gcr
  namespace: default # must be 'default' in MCI, even if app itself is not in default
spec:
  image: {{ .name }}
  interval: {{ .repository.syncInterval | default "5m0s" }}
  secretRef:
    name: flux-mci-registry-credential
{{- end -}}
