{{- $appName := include "web-service.name" . }}
{{- $targetPort := .Values.service.targetPort | default .Values.ports.containerHttpPort -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ $targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "web-service.selectorLabels" . | nindent 4 }}
