apiVersion: v1
entries:
  basic-web-service:
  - apiVersion: v2
    created: "2022-06-05T15:25:38.264383-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 298bdf381395bfac8f5b942b0ce1575921cbdb5b8aeaabbe7abcc8bbd68c73bd
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.10.tgz
    version: 0.2.10
  - apiVersion: v2
    created: "2022-06-05T15:25:38.269188-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: d16146493536ff9e40ad3529b8f99cb0659f64408ef9fc6d29cc73ffe529c267
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    created: "2022-06-05T15:25:38.268675-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: e1ce325e5aa1c1543fe0f6de9a821461329f6639c46852779caefd31e57e3690
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    created: "2022-06-05T15:25:38.268161-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 02cc4372317c262ac2b02437973129aef0f42594f71c15276bcdcacef0054be7
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    created: "2022-06-05T15:25:38.266986-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 33f40e7f1add3fc9ad8e4dc672a2c4f1832dd3bba90a6dec77d8da3ee383bc2a
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    created: "2022-06-05T15:25:38.266448-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 25665fc9b03602c10a523589dbc852c5bf6ef40864e538dc668d12896970f927
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    created: "2022-06-05T15:25:38.265945-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 7c8aeea21514ff4d1c406691f863c0068c12f3833f2c8baad5213d20f75a2cd9
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    created: "2022-06-05T15:25:38.265447-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 1fa1666cc539b210e8a886867b4826288534da48f1b23fcd5a92b7c3a4afd36c
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    created: "2022-06-05T15:25:38.26491-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 9c51a11a863d1d431826a0ef035004b7559ea037dc4b10df672ffda258bc989e
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.2.tgz
    version: 0.2.2
generated: "2022-06-05T15:25:38.263556-07:00"
