apiVersion: v1
entries:
  basic-web-service:
  - apiVersion: v2
    created: "2022-06-06T07:18:00.631483-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 58eefc2766c3f1c10a89a1822c1ff4f984f544fa91854662b179ce8393b3b858
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.14.tgz
    version: 0.2.14
  - apiVersion: v2
    created: "2022-06-06T07:18:00.630882-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 3f4268223cd3cb54370e4587657f3c9ffc2ebd8ff58c0a0f7d280a7aa266382f
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.13.tgz
    version: 0.2.13
  - apiVersion: v2
    created: "2022-06-06T07:18:00.630364-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 918e4a92999b41cd927f725c114c3a1f2328f6e3700545391adcf2695d3d6dab
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.12.tgz
    version: 0.2.12
  - apiVersion: v2
    created: "2022-06-06T07:18:00.629846-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: ad19c723de9b806b248094cd4ce09e4950ad09a6240289acf0a492bb725a15aa
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.11.tgz
    version: 0.2.11
  - apiVersion: v2
    created: "2022-06-06T07:18:00.629321-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 298bdf381395bfac8f5b942b0ce1575921cbdb5b8aeaabbe7abcc8bbd68c73bd
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.10.tgz
    version: 0.2.10
  - apiVersion: v2
    created: "2022-06-06T07:18:00.636566-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: d16146493536ff9e40ad3529b8f99cb0659f64408ef9fc6d29cc73ffe529c267
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    created: "2022-06-06T07:18:00.636101-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: e1ce325e5aa1c1543fe0f6de9a821461329f6639c46852779caefd31e57e3690
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    created: "2022-06-06T07:18:00.635557-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 02cc4372317c262ac2b02437973129aef0f42594f71c15276bcdcacef0054be7
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    created: "2022-06-06T07:18:00.635063-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 33f40e7f1add3fc9ad8e4dc672a2c4f1832dd3bba90a6dec77d8da3ee383bc2a
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    created: "2022-06-06T07:18:00.634529-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 25665fc9b03602c10a523589dbc852c5bf6ef40864e538dc668d12896970f927
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    created: "2022-06-06T07:18:00.633906-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 7c8aeea21514ff4d1c406691f863c0068c12f3833f2c8baad5213d20f75a2cd9
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    created: "2022-06-06T07:18:00.632532-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 1fa1666cc539b210e8a886867b4826288534da48f1b23fcd5a92b7c3a4afd36c
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    created: "2022-06-06T07:18:00.631996-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 9c51a11a863d1d431826a0ef035004b7559ea037dc4b10df672ffda258bc989e
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.2.tgz
    version: 0.2.2
generated: "2022-06-06T07:18:00.628502-07:00"
