apiVersion: v1
entries:
  basic-web-service:
  - apiVersion: v2
    created: "2022-06-03T13:51:19.934836-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 7c8aeea21514ff4d1c406691f863c0068c12f3833f2c8baad5213d20f75a2cd9
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    created: "2022-06-03T13:51:19.934349-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 1fa1666cc539b210e8a886867b4826288534da48f1b23fcd5a92b7c3a4afd36c
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    created: "2022-06-03T13:51:19.933802-07:00"
    description: 'A Helm chart for a basic web application that can deploy on a UW-IT
      Managed Container Infrastructure cluster. '
    digest: 9c51a11a863d1d431826a0ef035004b7559ea037dc4b10df672ffda258bc989e
    name: basic-web-service
    type: application
    urls:
    - basic-web-service-0.2.2.tgz
    version: 0.2.2
generated: "2022-06-03T13:51:19.933035-07:00"
