####
# Secret definitions for this deployment.
#
# --- database password ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grouper-db-account
  namespace: grouper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mosler-iam
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.domain }}/grouper/db/APP_USER
---
# --- database certificate key password ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grouper-db-client-key-password
  namespace: grouper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mosler-iam
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.domain }}/grouper/db/CERT_KEY_PASSWORD
---
# --- database client certificate and key ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grouper-db-client-cert
  namespace: grouper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mosler-iam
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.domain }}/grouper/db/client_cert
---
# --- Shibboleth encryption keys ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grouper-shib-keys
  namespace: grouper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mosler-iam
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.domain }}/grouper/shib
---
# --- Grouper encryption key ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grouper-app-config
  namespace: grouper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mosler-iam
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.domain }}/grouper/app-config
